### PR TITLE
Add slint lang tree-sitter

### PR DESCRIPTION
**Pull request by flukejones**
I don't know if there is anything else I need to do here. I have built and added the resulting lib to the grammars dir but the lang does not show up - I assume I need to also add the base support for lapce.

### CODE REVIEW

**Comment by panekj** [comment]
I'd rather not expand languages here, mostly due to the fact that all major grammars are added and this repository is only an interim artefact until Lapce uses grammars compiled to WASM (which are going to be available as plugins)

**Comment by flukejones** [comment]
@panekj what is the status on wasm version of grammer plugins?

**Comment by panekj** [comment]
Someone has to implement

**Comment by flukejones** [comment]
> Someone has to implement

So if it's not implemented then why can we not continue with PR?

**Comment by panekj** [comment]
Because it puts more work on me since I have to rebase/fix conflicts every time someone adds a language in lapce

**Comment by flukejones** [comment]
Can you enforce the submitters of PR to do rebase and conflict fix? I typically do this myself out of habit since projects like Gnome and Linux kernel enforce this.

**Pull request merged**
